language: python
python:
  - "2.7"
  - "3.6"

branches:
  only:
    - master

install:
  - travis_retry pip install pylint
  - travis_retry pip install -r requirements.txt

script:
  py.test --cov=app

after_success:
  - pylint
